-- calculating the number of employees for each distinct position in the employee table
DROP PROCEDURE IF EXISTS CountEmployeesByPosition;
CREATE PROCEDURE CountEmployeesByPosition(
    IN p_position VARCHAR(256)
)
BEGIN
    SELECT position, COUNT(1) as employee_count
    FROM employee
    WHERE position = p_position
    GROUP BY position;
END;

-- calculating the total revenue generated by the employee for the given month
DROP PROCEDURE IF EXISTS CalculateEmployeeRevenue;
CREATE PROCEDURE CalculateEmployeeRevenue(
    IN employee_name VARCHAR(256),
    IN month INT,
    IN year INT,
    OUT employee_name_out VARCHAR(256),
    OUT revenue INT
)
BEGIN
    SELECT MAX(e.name), SUM(p.amount)
    INTO employee_name_out, revenue
    FROM payment p
             INNER JOIN appointment a ON p.appointment_id = a.appointment_id
             INNER JOIN employee e ON a.employee_id = e.employee_id
    WHERE YEAR(a.date) = year
      AND MONTH(a.date) = month
      AND e.name = employee_name;
END;

-- calculating the average salary of employees in a specified department for a certain month and year
DROP PROCEDURE IF EXISTS CalculateDepartmentAverageSalary;

CREATE PROCEDURE CalculateDepartmentAverageSalary(
    INOUT department_name VARCHAR(256),
    IN month INT,
    IN year INT,
    OUT average_salary INT
)
BEGIN
    DECLARE total_salary INT;
    DECLARE employee_count INT;

    -- counting the total salary of employees in the department
    SELECT SUM(e.salary)
    INTO total_salary
    FROM employee e
             INNER JOIN appointment a ON e.employee_id = a.employee_id
    WHERE YEAR(a.date) = year
      AND MONTH(a.date) = month
      AND e.position = department_name;

    -- counting the number of employees in the department
    SELECT COUNT(1)
    INTO employee_count
    FROM employee
    WHERE position = department_name;

    -- calculating the average salary
    IF employee_count > 0 THEN
        SET average_salary = total_salary / employee_count;
    ELSE
        SET average_salary = 0;
    END IF;

    -- updating the department name with the modified value
    SET department_name = CONCAT('Updated ', department_name);
END;


-- testing the stored procedures
CALL CountEmployeesByPosition('Stylist');

CALL CalculateEmployeeRevenue('Alice Johnson', 2, 2024, @employee_name, @revenue);
SELECT @employee_name AS EmployeeName, @revenue AS TotalRevenue;

